
price_apis:
  alpha_vantage: "RU6W0PWAUZ0JYD0A"
  polygon: "6_TgTH0XU8AdgToOqMqfrEsE4PkwRJda"
  finnhub: "d0ng2fpr01qi1cve64bgd0ng2fpr01qi1cve64c0"
  yahoo_finance: ""

fundamental_apis:
  alpha_vantage: "RU6W0PWAUZ0JYD0A"
  finnhub: "d0ng2fpr01qi1cve64bgd0ng2fpr01qi1cve64c0"


sentiment_apis:
  alpha_vantage: "RU6W0PWAUZ0JYD0A"
  finnhub: "d0ng2fpr01qi1cve64bgd0ng2fpr01qi1cve64c0"

macro_apis:
  fred: "5ab3bfadeb631202a8dad2a52fd01821"
  quandl: "CchiUoMKN9thkVHWm_pd"

rate_limits:
  alpha_vantage: 5
  polygon: 100
  finnhub: 60
  fred: 120
  yahoo_finance: 1000
