logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    detailed:
      format: "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)d] - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
    simple:
      format: "%(levelname)s - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout

    file_debug:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: detailed
      filename: "logs/app_debug.log"
      maxBytes: 10485760  # 10 MB
      backupCount: 5
      encoding: utf8

    file_error:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: detailed
      filename: "logs/app_error.log"
      maxBytes: 5242880  # 5 MB
      backupCount: 3
      encoding: utf8

  loggers:
    root:
      level: DEBUG
      handlers:
        - console
        - file_debug

    data_collector:
      level: INFO
      handlers:
        - file_debug
      propagate: false

    model_trainer:
      level: DEBUG
      handlers:
        - file_debug
      propagate: false

    trading_engine:
      level: INFO
      handlers:
        - file_debug
      propagate: false

  root:
    level: DEBUG
    handlers:
      - console
      - file_debug
